name: test_for_solid_software
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'


dependencies:

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.5





dev_dependencies:

  flutter_test:
    sdk: flutter

  pubspec_dependency_sorter: ^1.0.4
  solid_lints: ^0.1.5



flutter: 
  uses-material-design: true
